# Generated by Django 3.0.7 on 2020-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
